name = "nextjs-starter"
main = "./.open-next/server-function/index.mjs"
compatibility_date = "2023-08-14"
compatibility_flags = ["nodejs_compat"]

# Bind a KV namespace to make the KV cache work
[[kv_namespaces]]
binding = "ASSETS"
id = "091b7bba31c14ba7a641e5e8cfe88f17"

# Bind a Durable Object namespace for the cache
[[durable_objects.bindings]]
name = "CACHE"
class_name = "Cache"
script_name = "nextjs-starter"

# Bind a Durable Object namespace for the image optimizer
[[durable_objects.bindings]]
name = "IMAGE_OPTIMIZER"
class_name = "ImageOptimizer"
script_name = "nextjs-starter"

# Define the Durable Objects that need to be migrated
[[migrations]]
tag = "v1"
new_classes = ["Cache", "ImageOptimizer"]

# Configure site if you're using static assets
[site]
bucket = "./.open-next/assets"